### ISSUE TITLE
v1.1.0-beta? release

### ISSUE THREAD

**Issue by Jeavon** [umbraco-community/UmbracoFileSystemProviders.Azure#123]
@JimBobSquarePants @idseefeld as we potentially have 2 new features in SAS token support and TLS configuration I'm thinking we should create a v1.1.0-beta release to get these new features some testing.

What do you think?

**Comment by JimBobSquarePants** [comment]
Yeah, sounds good to me. Better safe than sorry.

**Comment by Jeavon** [comment]
If you have a few minutes could you have a glance at https://github.com/JimBobSquarePants/UmbracoFileSystemProviders.Azure/pull/122 

I also think it makes sense to beta release as both of these features are loosely linked to the same features being added to the ImageProcessor CloudImageService for most usage. (I need to complete the TLS config PR for that too)

**Comment by idseefeld** [comment]
I agree, hopefully I have some time next weekend for testing.

**Comment by JimBobSquarePants** [comment]
@Jeavon The CloudImageService is on it's way out. I'm replacing it with a dedicated AzureImageService. 

https://github.com/JimBobSquarePants/ImageProcessor/blob/6bcfc369461c194c2c534405e9c54f4aa75bf8e7/src/ImageProcessor.Web.Plugins.AzureBlobCache/AzureImageService.cs

I don't need SAS token support for that because if the blob is private we simply stream it to the response.

Have had a look at #122 Can't see anything amiss, just a couple of questions.

**Comment by Jeavon** [comment]
@JimBobSquarePants cool! Perfect that I add the TLS config option to the AzureImageService then too.

**Comment by idseefeld** [comment]
@Jeavon hope my latest merge for sas parsing did not come to late for the 1.1.0-beta...

**Comment by Jeavon** [comment]
@idseefeld no rush, I'm not ready with TLS feature either

**Comment by idseefeld** [comment]
@Jeavon I had to change the SAS token change again :-(

**Comment by Jeavon** [comment]
@idseefeld is the SAS token feature stable yet or still WIP?

**Comment by tonygayter** [comment]
Is this beta going to be released soon? Im having issues with turning off TLS 1.0 and 1.1 and the stack trace is referring to this plugin. I hope this will resolve that

**Comment by idseefeld** [comment]
Hi Jeavon,should be stable and all test are running without failures. I'll add some documentation when it is released. 
Dirk
-------- Ursprüngliche Nachricht --------Von: Jeavon <notifications@github.com> Datum: 24.10.18  18:00  (GMT+01:00) An: "JimBobSquarePants/UmbracoFileSystemProviders.Azure" <UmbracoFileSystemProviders.Azure@noreply.github.com> Cc: Dirk Seefeld <dirk.seefeld@idseefeld.de>, Mention <mention@noreply.github.com> Betreff: Re: [JimBobSquarePants/UmbracoFileSystemProviders.Azure] v1.1.0-beta? release (#123) 
@idseefeld is the SAS token feature stable yet or still WIP?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/JimBobSquarePants/UmbracoFileSystemProviders.Azure","title":"JimBobSquarePants/UmbracoFileSystemProviders.Azure","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/JimBobSquarePants/UmbracoFileSystemProviders.Azure"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Jeavon in #123: @idseefeld is the SAS token feature stable yet or still WIP?"}],"action":{"name":"View Issue","url":"https://github.com/JimBobSquarePants/UmbracoFileSystemProviders.Azure/issues/123#issuecomment-432717970"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/JimBobSquarePants/UmbracoFileSystemProviders.Azure/issues/123#issuecomment-432717970",
"url": "https://github.com/JimBobSquarePants/UmbracoFileSystemProviders.Azure/issues/123#issuecomment-432717970",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [JimBobSquarePants/UmbracoFileSystemProviders.Azure] v1.1.0-beta? release (#123)",
"sections": [
{
"text": "",
"activityTitle": "**Jeavon**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@Jeavon",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"JimBobSquarePants/UmbracoFileSystemProviders.Azure\",\n\"issueId\": 123,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"JimBobSquarePants/UmbracoFileSystemProviders.Azure\",\n\"issueId\": 123\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/JimBobSquarePants/UmbracoFileSystemProviders.Azure/issues/123#issuecomment-432717970"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 387365071\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by idseefeld** [comment]
@Jeavon & @JimBobSquarePants 
I have created a wiki page about the SAS details in my fork. Because this is quite specific a wiki page seems to be a better place. Perhapse we can put a note in the _README.md_?
Looks like you cannot create pull requests for wikis :( 
But you may have a look https://github.com/idseefeld/UmbracoFileSystemProviders.Azure/wiki 
When you agree I'll copy the wiki over to this repo.

**Comment by gavinfaux** [comment]
Would proposed beta release address issue of allowing form uploads to be stored in separate secure container (not 'media') as discussed in https://github.com/JimBobSquarePants/UmbracoFileSystemProviders.Azure/issues/98. 

Or would one need to merge latest changes from current branch with fork if separate container support and latest fixes required? Just looking for guidance, thanks.

**Comment by JimBobSquarePants** [comment]
@gavinfaux No, and I don't think it the workaround should be added either. This is an issue form the Forms project and pressure should be put on Umbraco to fix their issues.

**Comment by Jeavon** [comment]
@idseefeld could you please create a PR using the develop branch as source and master as the target? This will allow myself and @JimBobSquarePants the opportunity to review all the changes you've made. Please don't accept this PR until it's been reviewed by us.

**Comment by gavinfaux** [comment]
@JimBobSquarePants agree regarding fix via Umbraco Forms; we don't mind building from latest source with workaround on this occasion; Umbraco Cloud support kind of suggest coming here and no feedback available for Forms regarding pending releases with required functionality as yet.

**Comment by joelblake1** [comment]
Hi @Jeavon @JimBobSquarePants,
Is there any ETA on the beta release yet? I've tried the version in develop with SAS and it works great! 👍 
@idseefeld Great work on the wiki page as well. Very easy to follow.

**Comment by Jeavon** [comment]
v1.1.0 has been released
